stages:
  training:
    cmd: kedro run --pipeline training
    deps:
      - data/01_raw/companies.csv
      - data/01_raw/reviews.csv
      - data/01_raw/shuttles.xlsx
      - src/kedro_mlops_tp/pipelines/data_processing/nodes.py
      - src/kedro_mlops_tp/pipelines/data_processing/pipeline.py
      - src/kedro_mlops_tp/pipelines/data_science/nodes.py
      - src/kedro_mlops_tp/pipelines/data_science/pipeline.py
    outs:
      - data/02_intermediate/preprocessed_companies.parquet
      - data/02_intermediate/preprocessed_shuttles.parquet
      - data/03_primary/model_input_table.parquet
      - data/05_model_input/x_train.parquet
      - data/08_reporting/ydata_report.html
    params:
      - conf/base/parameters_data_science.yml:
          - model_options